EventManager.PL.New/Controllers/AddressController.cs
using System.Web.Mvc;
using EventManager.AccountPolicy;
using EventManager.BL.DTOs.Addresses;
using EventManager.BL.DTOs.Filters;
using EventManager.BL.Facades;

namespace EventManager.PL.Controllers
{
    [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
    public class AddressController : Controller
    {
        public EventFacade EventFacade { get; set; }

        public ActionResult Index()
        {
            var addresses = EventFacade.ListAddresses(new AddressFilter());
            return View(addresses);
        }

        public ActionResult Details(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var address = EventFacade.GetAddress(id);
            return View(address);
        }

        public ActionResult Create()
        {
            return View(new AddressCreateDTO());
        }

        [HttpPost]
        public ActionResult Create(AddressCreateDTO address)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", address);
            }

            try
            {
                EventFacade.CreateAddress(address);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create", address);
            }
        }

        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var address = EventFacade.GetAddress(id);
            return View(address);
        }

        [HttpPost]
        public ActionResult Edit(int id, AddressDTO address)
        {
            if (!ModelState.IsValid)
            {
                return View(address);
            }

            try
            {
                EventFacade.UpdateAddress(address);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(address);
            }
        }

        public ActionResult Delete(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            EventFacade.DeleteAddress(id);
            return RedirectToAction("Index");
        }
    }
}

EventManager.PL.New/Controllers/Admin/UserController.cs
using System.Web.Mvc;
using EventManager.AccountPolicy;
using EventManager.BL.DTOs.Filters;
using EventManager.BL.DTOs.Users;
using EventManager.BL.Facades;
using EventManager.PL.ViewModels.Users;

namespace EventManager.PL.Controllers.Admin
{
    [Authorize(Roles = Claims.Admin)]
    public class UserController : Controller
    {
        public UserFacade UserFacade { get; set; }
        
        public ActionResult Index()
        {
            var users = UserFacade.ListUsers(new UserFilter());
            return View(users);
        }

        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var user = UserFacade.GetUser(id);
            return View(CreateUserViewModel(user));
        }
        
        [HttpPost]
        public ActionResult Edit(int id, UserDTO user)
        {
            if (!ModelState.IsValid)
            {
                return View(CreateUserViewModel(user));
            }

            try
            {
                UserFacade.UpdateUser(user);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        private UserViewModel CreateUserViewModel(UserDTO user)
        {
            return new UserViewModel
            {
                User = user,
                UserRoles = new SelectList(new[] { Claims.Member, Claims.Organizer }, user.Role)
            };
        }
    }
}

EventManager.PL.New/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EventManager.AccountPolicy;
using EventManager.BL.DTOs.Addresses;
using EventManager.BL.DTOs.Events;
using EventManager.BL.DTOs.Filters;
using EventManager.BL.DTOs.Registrations;
using EventManager.BL.DTOs.Users;
using EventManager.BL.Facades;
using EventManager.BL.Miscellaneous;
using EventManager.PL.ViewModels.Events;
using X.PagedList;

namespace EventManager.PL.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly string filterSessionKey = "filter";
        
        public EventFacade EventFacade { get; set; }
        public UserFacade UserFacade { get; set; }
        public RegistrationFacade RegistrationFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            var filter = Session[filterSessionKey] as EventFilter ?? new EventFilter();
            var events = EventFacade.ListEvents(new EventFilter { SortCriteria = EventSortCriteria.Date }, page);

            return View(CreateEventListViewModel(events, filter));
        }

        [HttpPost]
        public ActionResult Index(EventListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;
            var events = EventFacade.ListEvents(model.Filter);

            return View(CreateEventListViewModel(events, model.Filter));
        }

        public ActionResult Detail(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var eventDetail = EventFacade.GetEventDetail(id);
            var organizer = UserFacade.GetUser(eventDetail.Event.UserId);
            var address = EventFacade.GetAddress(eventDetail.Event.AddressId);
            
            return View(CreateEventDetailViewModel(eventDetail, address, organizer));
        }

        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Create()
        {
            var addresses = EventFacade.ListAddresses(new AddressFilter());
            var organizers = UserFacade.ListUsers(new UserFilter { Role = Claims.Organizer });

            return View(CreateEventViewModel(new EventDTO(), addresses, organizers));
        }

        [HttpPost]
        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Create(EventViewModel @event)
        {
            if (!ModelState.IsValid)
            {
                var addresses = EventFacade.ListAddresses(new AddressFilter());
                var organizers = UserFacade.ListUsers(new UserFilter { Role = Claims.Organizer });

                return View(CreateEventViewModel(@event.EventData, addresses, organizers));
            }

            EventFacade.CreateEvent(@event.EventData);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Register(int userid, int eventid)
        {
            if (eventid <= 0)
            {
                return RedirectToAction("Index");
            }

            try
            {
                RegistrationFacade.Register(new RegistrationCreateDTO
                {
                    EventId = eventid,
                    UserId = userid
                });
            }
            catch (Exception)
            {
               
            }

            return RedirectToAction("Detail", new { id = eventid });
        }

        public ActionResult Unregister(int registrationid, int eventid)
        {
            if (eventid <= 0 && registrationid <= 0)
            {
                return RedirectToAction("Index");
            }

            try
            {
                RegistrationFacade.Unregister(registrationid);
            }
            catch (Exception ex)
            {
                //TODO log
            }

            return RedirectToAction("Detail", new { id = eventid });
        }

        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var @event = EventFacade.GetEvent(id);
            var addresses = EventFacade.ListAddresses(new AddressFilter());
            var organizers = UserFacade.ListUsers(new UserFilter {Role = Claims.Organizer});

            return View(CreateEventViewModel(@event, addresses, organizers));
        }
        
        [HttpPost]
        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Edit(int id, EventViewModel @event)
        {
            if (!ModelState.IsValid)
            {
                return View(@event);
            }

            try
            {
                EventFacade.UpdateEvent(@event.EventData);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(@event);
            }
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        private EventViewModel CreateEventViewModel(EventDTO eventDto, IEnumerable<AddressDTO> addresses,
            IEnumerable<UserDTO> organizers)
        {
            return new EventViewModel
            {
                EventData = eventDto,
                AddressList = new SelectList(addresses, "Id", "FullAddress"),
                Organizers = new SelectList(organizers, "Id", "FullName")
            };
        }

        private EventDetailViewModel CreateEventDetailViewModel(EventDetailDTO eventDto, AddressDTO address,
            UserDTO organizer)
        {
            return new EventDetailViewModel
            {
                EventDetail = eventDto,
                Address = address,
                Organizer = organizer
            };
        }

        private EventListViewModel CreateEventListViewModel(EventPagedListResultDTO events, EventFilter filter)
        {
            return  new EventListViewModel
            {
                Filter = filter,
                EventsPage = new StaticPagedList<EventDTO>(events.ResultPageData, events.RequestedPage, 
                EventFacade.EventPageSize, events.TotalResultCount)
            };
        }
    }
}

EventManager.PL.New/Views/Shared/_Layout.cshtml
@using EventManager.AccountPolicy
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Event Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Event manager", "Index", "Event", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("Events", "Index", "Event")</li>

                    @if (User.IsInRole(Claims.Admin))
                    {
                        <li>@Html.ActionLink("AddressList", "Index", "Address")</li>
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                    }
                    else if (User.IsInRole(Claims.Organizer))
                    {
                        <li>@Html.ActionLink("AddressList", "Index", "Address")</li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span> @User.Identity.Name.Split('@')[0] <b class="caret grey"></b></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Account management</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span><b class="caret grey"></b></a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header">Get started</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Register", "Register", "Account")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                            </ul>
                        </li>
                        }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-muted pull-right">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>