EventManager.PL.New/ViewModels/Events/EventDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using EventManager.BL.DTOs.Addresses;
using EventManager.BL.DTOs.EventReviews;
using EventManager.BL.DTOs.Events;
using EventManager.BL.DTOs.Registrations;
using EventManager.BL.DTOs.Users;

namespace EventManager.PL.ViewModels.Events
{
    public class EventDetailViewModel
    {
        public EventDetailDTO EventDetail { get; set; }
        public AddressDTO Address { get; set; }
        public UserDTO Organizer { get; set; }
    }
}

EventManager.PL.New/ViewModels/Events/EventListViewModel.cs
using EventManager.BL.DTOs.Events;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventManager.BL.DTOs.Filters;
using EventManager.BL.Miscellaneous;
using X.PagedList;

namespace EventManager.PL.ViewModels.Events
{
    public class EventListViewModel
    {
        public IPagedList<EventDTO> EventsPage { get; set; }
        public EventFilter Filter { get; set; }
        public SelectList AllSortCriteria => new SelectList(Enum.GetNames(typeof(EventSortCriteria)).ToList());
    }
}

EventManager.PL.New/ViewModels/Events/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventManager.BL.DTOs.Events;

namespace EventManager.PL.ViewModels.Events
{
    public class EventViewModel
    {
        public EventDTO EventData { get; set; }
        public SelectList AddressList { get; set; }
        public SelectList Organizers { get; set; }
    }
}

EventManager.PL.New/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EventManager.AccountPolicy;
using EventManager.BL.DTOs.Addresses;
using EventManager.BL.DTOs.Events;
using EventManager.BL.DTOs.Filters;
using EventManager.BL.DTOs.Registrations;
using EventManager.BL.DTOs.Users;
using EventManager.BL.Facades;
using EventManager.BL.Miscellaneous;
using EventManager.PL.ViewModels.Events;
using X.PagedList;

namespace EventManager.PL.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly string filterSessionKey = "filter";
        
        public EventFacade EventFacade { get; set; }
        public UserFacade UserFacade { get; set; }
        public RegistrationFacade RegistrationFacade { get; set; }

        public ActionResult Index(int page = 1)
        {
            var filter = Session[filterSessionKey] as EventFilter ?? new EventFilter();
            var events = EventFacade.ListEvents(new EventFilter { SortCriteria = EventSortCriteria.Date }, page);

            return View(CreateEventListViewModel(events, filter));
        }

        [HttpPost]
        public ActionResult Index(EventListViewModel model)
        {
            Session[filterSessionKey] = model.Filter;
            var events = EventFacade.ListEvents(model.Filter);

            return View(CreateEventListViewModel(events, model.Filter));
        }

        public ActionResult Detail(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var eventDetail = EventFacade.GetEventDetail(id);
            var organizer = UserFacade.GetUser(eventDetail.Event.UserId);
            var address = EventFacade.GetAddress(eventDetail.Event.AddressId);
            
            return View(CreateEventDetailViewModel(eventDetail, address, organizer));
        }

        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Create()
        {
            var addresses = EventFacade.ListAddresses(new AddressFilter());
            var organizers = UserFacade.ListUsers(new UserFilter { Role = Claims.Organizer });

            return View(CreateEventViewModel(new EventDTO(), addresses, organizers));
        }

        [HttpPost]
        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Create(EventViewModel @event)
        {
            if (!ModelState.IsValid)
            {
                var addresses = EventFacade.ListAddresses(new AddressFilter());
                var organizers = UserFacade.ListUsers(new UserFilter { Role = Claims.Organizer });

                return View(CreateEventViewModel(@event.EventData, addresses, organizers));
            }

            EventFacade.CreateEvent(@event.EventData);

            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Register(int userid, int eventid)
        {
            if (eventid <= 0)
            {
                return RedirectToAction("Index");
            }

            try
            {
                RegistrationFacade.Register(new RegistrationCreateDTO
                {
                    EventId = eventid,
                    UserId = userid
                });
            }
            catch (Exception)
            {
               
            }

            return RedirectToAction("Detail", new { id = eventid });
        }

        public ActionResult Unregister(int registrationid, int eventid)
        {
            if (eventid <= 0 && registrationid <= 0)
            {
                return RedirectToAction("Index");
            }

            try
            {
                RegistrationFacade.Unregister(registrationid);
            }
            catch (Exception ex)
            {
                //TODO log
            }

            return RedirectToAction("Detail", new { id = eventid });
        }

        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var @event = EventFacade.GetEvent(id);
            var addresses = EventFacade.ListAddresses(new AddressFilter());
            var organizers = UserFacade.ListUsers(new UserFilter {Role = Claims.Organizer});

            return View(CreateEventViewModel(@event, addresses, organizers));
        }
        
        [HttpPost]
        [Authorize(Roles = Claims.Organizer + ", " + Claims.Admin)]
        public ActionResult Edit(int id, EventViewModel @event)
        {
            if (!ModelState.IsValid)
            {
                return View(@event);
            }

            try
            {
                EventFacade.UpdateEvent(@event.EventData);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(@event);
            }
        }

        public ActionResult ClearFilter()
        {
            Session[filterSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        private EventViewModel CreateEventViewModel(EventDTO eventDto, IEnumerable<AddressDTO> addresses,
            IEnumerable<UserDTO> organizers)
        {
            return new EventViewModel
            {
                EventData = eventDto,
                AddressList = new SelectList(addresses, "Id", "FullAddress"),
                Organizers = new SelectList(organizers, "Id", "FullName")
            };
        }

        private EventDetailViewModel CreateEventDetailViewModel(EventDetailDTO eventDto, AddressDTO address,
            UserDTO organizer)
        {
            return new EventDetailViewModel
            {
                EventDetail = eventDto,
                Address = address,
                Organizer = organizer
            };
        }

        private EventListViewModel CreateEventListViewModel(EventPagedListResultDTO events, EventFilter filter)
        {
            return  new EventListViewModel
            {
                Filter = filter,
                EventsPage = new StaticPagedList<EventDTO>(events.ResultPageData, events.RequestedPage, 
                EventFacade.EventPageSize, events.TotalResultCount)
            };
        }
    }
}

EventManager.PL.New/Controllers/PaymentController.cs
using System.Diagnostics;
using System.Web.Mvc;
using EventManager.BL.DTOs.Registrations;
using EventManager.BL.Facades;

namespace EventManager.PL.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        public RegistrationFacade RegistrationFacade { get; set; }

        public ActionResult Pay(int registrationid, int eventid)
        {
            if (eventid <= 0 && registrationid <= 0)
            {
                return RedirectToAction("Detail", "Event", new { id = eventid });
            }

            var registration = RegistrationFacade.GetRegistration(registrationid);
            return View(registration);
        }

        [HttpPost]
        public ActionResult Pay(RegistrationDTO registrationDto)
        {
            Debug.WriteLine(registrationDto);
            RegistrationFacade.UpdateRegistration(registrationDto);
            return RedirectToAction("Detail", "Event", new { id = registrationDto.EventId });
        }
    }
}

EventManager.PL.New/Controllers/ReviewController.cs
using System.Web.Mvc;
using EventManager.AccountPolicy;
using EventManager.BL.DTOs.EventReviews;
using EventManager.BL.Facades;

namespace EventManager.PL.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        public EventFacade EventFacade { get; set; }

        public ActionResult Create(int eventId)
        {
            return View(new EventReviewCreateDTO { EventId = eventId });
        }

        [HttpPost]
        public ActionResult Create(int eventId, EventReviewCreateDTO reviewDto)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", reviewDto);
            }

            try
            {
                EventFacade.CreateReview(reviewDto);
                return RedirectToAction("Detail", "Event", new { id = reviewDto.EventId });
            }
            catch
            {
                return View("Create", reviewDto);
            }
        }

        [Authorize(Roles = Claims.Admin)]
        public ActionResult Edit(int id, int reviewId)
        {
            if (reviewId <= 0)
            {
                return RedirectToAction("Detail", "Event", new { id = id });
            }

            var review = EventFacade.GetReview(reviewId);
            return View(review);
        }

        [HttpPost]
        [Authorize(Roles = Claims.Admin)]
        public ActionResult Edit(int id, EventReviewDTO reviewDto)
        {
            if (!ModelState.IsValid)
            {
                return View(reviewDto);
            }

            try
            {
                EventFacade.UpdateReview(reviewDto);
                return RedirectToAction("Detail", "Event", new { id = reviewDto.EventId });
            }
            catch
            {
                return View(reviewDto);
            }
        }

        [Authorize(Roles = Claims.Admin)]
        public ActionResult Delete(int id, int reviewId)
        {
            if (reviewId <= 0)
            {
                return RedirectToAction("Detail", "Event", new { id = id });
            }

            EventFacade.DeleteReview(reviewId);
            return RedirectToAction("Detail", "Event", new { id = id });
        }
    }
}

EventManager.PL.New/Views/Event/Create.cshtml
@model EventManager.PL.ViewModels.Events.EventViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Lecturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Lecturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Lecturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.EventData.Date, new { htmlAttributes = new { @class = "form-control" } })
                
                @Html.ValidationMessageFor(model => model.EventData.Date, "", new {@class = "text-danger"})@*//TODO change format*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.End, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventData.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventData.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventData.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <strong>Address</strong>
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EventData.AddressId, Model.AddressList, "Select...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventData.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <strong>Organizer</strong>
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EventData.UserId, Model.Organizers, "Select...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventData.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventManager.PL.New/Views/Event/Detail.cshtml
@using EventManager.AccountPolicy
@using EventManager.DAL.Enums
@model EventManager.PL.ViewModels.Events.EventDetailViewModel

@{
    ViewBag.Title = "Detail";
}

<div class="col-md-offset-1">
    <h2>@Html.DisplayFor(model => model.EventDetail.Event.Title)</h2>
    <div class="row">
        <div class="col-md-4">
            <p>
                @Html.DisplayFor(model => model.EventDetail.Event.Description)
            </p>
        </div>
        <div class="col-md-4 col-md-offset-1">
            <div class="panel panel-info">
                <div class="panel-heading">Time and Address</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="box">
                                <span class="control-label">
                                    <strong>
                                        @Model.EventDetail.Event.Date.Add(@Model.EventDetail.Event.Start) -
                                        @Html.DisplayFor(model => model.EventDetail.Event.End)
                                    </strong>
                                </span>
                            </div>
                            <div class="box">
                                <span class="control-label">
                                    <strong>@Html.DisplayNameFor(model => model.Address):</strong>
                                    @Html.DisplayFor(model => model.Address.FullAddress)
                                </span>
                            </div>
                            <div class="box">
                                <span class="control-label">
                                    <strong>@Html.DisplayNameFor(model => model.EventDetail.Event.Lecturer):</strong>
                                    @Html.DisplayFor(model => model.EventDetail.Event.Lecturer)
                                </span>
                            </div>
                            <div class="box">
                                <span class="control-label">
                                    <strong>@Html.DisplayNameFor(model => model.Organizer):</strong>
                                    @Html.DisplayFor(model => model.Organizer.FullName)
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                @if (!Model.EventDetail.IsEnded)
            {
                    <div class="panel-heading">Registrations</div>
                    <div class="panel-body">
                        <div class="row">
                            <dl class="dl-horizontal">
                                <dt>
                                    Accepted:
                                </dt>
                                <dd>
                                    @Model.EventDetail.Registrations.Count(c => c.State == RegistrationState.Accepted)
                                </dd>
                                @if (Model.EventDetail.Event.Fee != 0)
                                {
                                    <dt>
                                        Unpaid:
                                    </dt>
                                    <dd>
                                        @Model.EventDetail.Registrations.Count(c => c.State == RegistrationState.Unpaid)
                                    </dd>
                                }
                                <dt>
                                    @Html.DisplayNameFor(model => model.EventDetail.Event.Capacity):
                                </dt>

                                @if (Model.EventDetail.Event.Capacity.HasValue)
                                {
                                    <dd>
                                        @Html.DisplayFor(model => model.EventDetail.Event.Capacity)
                                    </dd>
                                }
                                else
                                {
                                    <dd>
                                        unlimited
                                    </dd>
                                }
                                <dt>
                                    @Html.DisplayNameFor(model => model.EventDetail.Event.Fee):
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.EventDetail.Event.Fee)
                                </dd>
                            </dl>
                            <p class="text-center">
                                @if (Model.EventDetail.Registrations.All(a => a.UserId != 2))
                                {
                                    <input type="button" class="btn btn-primary" value="Register"
                                           onclick="location.href = '@Url.Action("Register", "Event", new {userId = 2, eventId = Model.EventDetail.Event.Id})'" />
                                }
                                else
                                {
                                    <input type="button" class="btn btn-danger" value="Unregister"
                                           onclick="location.href = '@Url.Action("Unregister", "Event", new
                                                                 {
                                                                     registrationid = Model.EventDetail.Registrations.FirstOrDefault(f => f.UserId == 2)?.Id ?? 0,
                                                                     eventId = Model.EventDetail.Event.Id
                                                                 })'" />

                                    if (Model.EventDetail.Event.Fee != 0 && Model.EventDetail.Registrations.FirstOrDefault(f => f.UserId == 2)?.State == RegistrationState.Unpaid)
                                    {
                                        <input type="button" class="btn btn-primary" value="Pay fee"
                                               onclick="location.href = '@Url.Action("Pay", "Payment", new
                                                                     {
                                                                         registrationid = Model.EventDetail.Registrations.FirstOrDefault(f => f.EventId == Model.EventDetail.Event.Id
                                                                         && f.UserId == 2)?.Id ?? 0,
                                                                         eventId = Model.EventDetail.Event.Id
                                                                     })'" />
                                    }
                                }
                            </p>
                        </div>
                    </div>
                }
                else
                {
                    <div class="panel-heading">After event</div>
                    <div class="panel-body">
                        <div class="row">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.EventDetail.AverageRating)
                                </dt>
                                <dd>
                                    @($"{Model.EventDetail.AverageRating:0.0}") / 5 (@Model.EventDetail.Reviews.Count() review(s))
                                </dd>
                            </dl>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @if (Model.EventDetail.IsEnded)
    {
        <div class="row">
            <div class="row col-md-9">
                <button type="submit" class="btn btn-primary" onclick="location.href = '@Url.Action("Create", "Review", new {eventId = Model.EventDetail.Event.Id})'">
                    <i class="glyphicon glyphicon-plus"></i> Add review
                </button>
                <h4>User reviews:</h4>
            </div>

            @{
                foreach (var review in Model.EventDetail.Reviews)
                {
                    <div class="col-md-9 top-buffer-small  list-group-item-nonclickable">

                        @if (review.Rating >= 4.0)
                        {
                            <h3>
                                <strong class="text-success">@review.Rating</strong> / 5
                            </h3>
                        }
                        else
                        {
                            if (review.Rating >= 2.0)
                            {
                                <h3>
                                    <strong class="text-warning">@review.Rating</strong> / 5
                                </h3>
                            }
                            else
                            {
                                <h3>
                                    <strong class="text-danger">@review.Rating</strong> / 5
                                </h3>
                            }
                        }

                        @{
                            if (!string.IsNullOrEmpty(review.Review))
                            {
                                <div class="row">
                                    <p class="text col-sm-12">
                                        <strong>@Html.DisplayFor(arg => review.Author)</strong>: <i>"@Html.DisplayFor(arg => review.Review)"</i>
                                    </p>
                                </div>
                            }
                        }

                        @if (User.IsInRole(Claims.Admin))
                        {
                            @Html.ActionLink("Edit review", "Edit", "Review", new { id = Model.EventDetail.Event.Id, reviewId = review.Id }, null)
                            <br />
                            @Html.ActionLink("Delete review", "Delete", "Review", new { id = Model.EventDetail.Event.Id, reviewId = review.Id }, null)
                        }

                    </div>
                            }
            }
        </div>
                            }
<div>
    <br />
    <p>
        @if (User.IsInRole(Claims.Admin) || User.IsInRole(Claims.Organizer))
        {
            @Html.ActionLink("Edit event", "Edit", new {id = Model.EventDetail.Event.Id})
        }
        <br/>
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>
</div>